modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mods]]
    modId = "supplementaries"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"

    updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/1.20/forge/update.json"


[modproperties.supplementaries]
    catalogueItemIcon = "supplementaries:globe" #catalogue icon
    configuredBackground = "supplementaries:textures/block/blackstone_tiles.png"

[[dependencies.supplementaries]]
    modId = "forge"
    mandatory = true
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "moonlight"
    mandatory = true
    versionRange = "[${required_moonlight_version},]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.19-1.2.0,]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "quark"
    mandatory = false
    versionRange = "[1.19-3.4-404,]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "create"
    mandatory = false
    versionRange = "[6.0.0,]"
    ordering = "AFTER"
    side = "BOTH"



